from typing import List, Optional, Any, Literal, Dict
from pydantic import BaseModel, Field

class FilterCondition(BaseModel):
    """Deterministic filter condition for Pandas querying."""
    column: str = Field(description="Column name to filter upon")
    operator: Literal["eq", "neq", "gt", "gte", "lt", "lte", "contains", "in"] = Field(
        default="eq",
        description="Filter comparison operator: eq (==), neq (!=), gt (>), gte (>=), lt (<), lte (<=), contains, in"
    )
    value: Any = Field(description="Target filter value or list of values")

class SortConfig(BaseModel):
    """Sorting configuration for aggregation/table results."""
    column: str = Field(description="Column name to sort by")
    direction: Literal["asc", "desc"] = Field(default="desc", description="Sorting direction: 'asc' or 'desc'")

class AnalysisPlan(BaseModel):
    """
    Structured plan generated by Manager Agent.
    Strictly declarative - no arbitrary code allowed.
    """
    objective: str = Field(description="Human-readable goal of the analysis")
    metric: Optional[str] = Field(default=None, description="Target numerical metric column (e.g., 'Gross_Revenue')")
    operation: Literal[
        "sum",
        "mean",
        "median",
        "min",
        "max",
        "count",
        "value_counts",
        "describe",
        "distribution"
    ] = Field(
        default="sum",
        description="Aggregation operation to execute with Pandas"
    )
    group_by: List[str] = Field(default_factory=list, description="Categorical dimension(s) to group by (e.g. ['Product_Name'])")
    filters: List[FilterCondition] = Field(default_factory=list, description="List of filtering criteria")
    sort: Optional[SortConfig] = Field(default=None, description="Optional sorting configuration")
    limit: Optional[int] = Field(default=10, description="Maximum number of rows to return (Top-N)")
    date_column: Optional[str] = Field(default=None, description="Optional date column if time-slicing is needed")
    date_filter: Optional[str] = Field(default=None, description="Optional date expression (e.g., '2026-07' or 'July 2026')")
    explanation: Optional[str] = Field(default=None, description="Manager Agent's rationale for this analytical strategy")

class ColumnProfile(BaseModel):
    """Statistical summary of a single dataset column."""
    name: str
    dtype: str
    null_count: int
    null_percentage: float
    unique_count: int
    is_numeric: bool
    is_categorical: bool
    is_date: bool
    sample_values: List[Any] = Field(default_factory=list)

class DatasetProfile(BaseModel):
    """Comprehensive structural and statistical profile of an uploaded dataset."""
    dataset_id: str
    filename: str
    row_count: int
    column_count: int
    columns: List[ColumnProfile]
    numeric_columns: List[str]
    categorical_columns: List[str]
    date_columns: List[str]
    sample_rows: List[Dict[str, Any]]
    file_size_bytes: int
    created_at: str
