import React, { useState } from 'react';
import { AnalysisReport, Dataset } from '../../types';
import {
  FileText,
  Download,
  FileSpreadsheet,
  Printer,
  CheckCircle2,
  AlertTriangle,
  Lightbulb,
  Compass,
  HelpCircle,
  Copy,
  Check,
} from 'lucide-react';

interface ReportViewerProps {
  report: AnalysisReport;
  datasetName: string;
  question: string;
  activeDataset: Dataset | null;
}

export const ReportViewer: React.FC<ReportViewerProps> = ({
  report,
  datasetName,
  question,
  activeDataset,
}) => {
  const [copied, setCopied] = useState(false);

  const handleDownloadMarkdown = () => {
    const mdContent = `# AI Analysis Report: ${question}
**Dataset:** ${datasetName}
**Generated By:** AutonomousAI Multi-Agent System
**Date:** ${new Date().toLocaleDateString()}

---

## Executive Summary
${report.executiveSummary}

## Key Findings
${report.keyFindings.map((f) => `- ${f}`).join('\n')}

## Supporting Evidence
${report.supportingEvidence.map((e) => `- ${e}`).join('\n')}

## Detected Patterns
${report.detectedPatterns.map((p) => `- ${p}`).join('\n')}

## Potential Anomalies
${report.potentialAnomalies.map((a) => `- ${a}`).join('\n')}

## Recommended Investigation
${report.recommendedInvestigation.map((r) => `- ${r}`).join('\n')}

## Data Limitations
${report.dataLimitations.map((l) => `- ${l}`).join('\n')}
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Analysis_Report_${Date.now()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportCsv = () => {
    if (!activeDataset) return;
    const headers = activeDataset.columns.map((c) => `"${c.name}"`).join(',');
    const rows = activeDataset.previewRows.map((r) =>
      activeDataset.columns
        .map((c) => {
          const val = r[c.name];
          if (val === null || val === undefined) return '';
          return `"${String(val).replace(/"/g, '""')}"`;
        })
        .join(',')
    );
    const csvContent = [headers, ...rows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `${activeDataset.filename || 'dataset'}_export.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleGeneratePdf = () => {
    window.print();
  };

  const handleCopyReport = () => {
    const text = `Executive Summary:\n${report.executiveSummary}\n\nKey Findings:\n${report.keyFindings.join('\n')}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-6 shadow-sm space-y-6">
      {/* Header and Action Buttons */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-5">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-500/10 text-indigo-400">
              <FileText className="h-4 w-4" />
            </div>
            <h3 className="text-lg font-bold text-white tracking-tight">
              AI Analysis Report
            </h3>
          </div>
          <p className="text-xs text-slate-400">
            Synthesized and validated by Report Agent from raw data & business rules
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-2.5">
          <button
            onClick={handleCopyReport}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 transition-colors"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                <span>Copy</span>
              </>
            )}
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-500 rounded-lg shadow-sm transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download Report</span>
          </button>

          <button
            onClick={handleExportCsv}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 transition-colors"
          >
            <FileSpreadsheet className="h-3.5 w-3.5 text-emerald-400" />
            <span>Export CSV</span>
          </button>

          <button
            onClick={handleGeneratePdf}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 transition-colors"
          >
            <Printer className="h-3.5 w-3.5 text-cyan-400" />
            <span>Generate PDF</span>
          </button>
        </div>
      </div>

      {/* Structured Sections */}
      <div className="space-y-6 text-slate-200">
        {/* 1. Executive Summary */}
        <section className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 space-y-2">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-400 font-mono">
            <Lightbulb className="h-3.5 w-3.5" />
            <span>1. Executive Summary</span>
          </div>
          <p className="text-sm text-slate-200 leading-relaxed font-normal">
            {report.executiveSummary}
          </p>
        </section>

        {/* 2. Key Findings & 3. Supporting Evidence (Side by Side) */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Key Findings */}
          <section className="p-4 rounded-xl bg-slate-950/40 border border-slate-800 space-y-2.5">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-cyan-400 font-mono">
              <CheckCircle2 className="h-3.5 w-3.5" />
              <span>2. Key Findings</span>
            </div>
            <ul className="space-y-2 text-xs text-slate-300">
              {report.keyFindings.map((finding, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-cyan-400 font-mono font-bold shrink-0 mt-0.5">
                    •
                  </span>
                  <span>{finding}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Supporting Evidence */}
          <section className="p-4 rounded-xl bg-slate-950/40 border border-slate-800 space-y-2.5">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-emerald-400 font-mono">
              <Compass className="h-3.5 w-3.5" />
              <span>3. Supporting Evidence</span>
            </div>
            <ul className="space-y-2 text-xs text-slate-300">
              {report.supportingEvidence.map((evidence, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-emerald-400 font-mono font-bold shrink-0 mt-0.5">
                    ✓
                  </span>
                  <span>{evidence}</span>
                </li>
              ))}
            </ul>
          </section>
        </div>

        {/* 4. Detected Patterns & 5. Potential Anomalies */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Detected Patterns */}
          <section className="p-4 rounded-xl bg-slate-950/40 border border-slate-800 space-y-2.5">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-purple-400 font-mono">
              <FileText className="h-3.5 w-3.5" />
              <span>4. Detected Patterns</span>
            </div>
            <ul className="space-y-2 text-xs text-slate-300">
              {report.detectedPatterns.map((pat, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-purple-400 font-mono font-bold shrink-0 mt-0.5">
                    •
                  </span>
                  <span>{pat}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Potential Anomalies */}
          <section className="p-4 rounded-xl bg-slate-950/40 border border-slate-800 space-y-2.5">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-amber-400 font-mono">
              <AlertTriangle className="h-3.5 w-3.5" />
              <span>5. Potential Anomalies</span>
            </div>
            <ul className="space-y-2 text-xs text-slate-300">
              {report.potentialAnomalies.map((anom, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-amber-400 font-mono font-bold shrink-0 mt-0.5">
                    !
                  </span>
                  <span>{anom}</span>
                </li>
              ))}
            </ul>
          </section>
        </div>

        {/* 6. Recommended Investigation & 7. Data Limitations */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Recommended Investigation */}
          <section className="p-4 rounded-xl bg-slate-950/40 border border-slate-800 space-y-2.5">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-400 font-mono">
              <Compass className="h-3.5 w-3.5" />
              <span>6. Recommended Investigation</span>
            </div>
            <ul className="space-y-2 text-xs text-slate-300">
              {report.recommendedInvestigation.map((rec, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-indigo-400 font-mono font-bold shrink-0 mt-0.5">
                    →
                  </span>
                  <span>{rec}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Data Limitations */}
          <section className="p-4 rounded-xl bg-slate-950/40 border border-slate-800 space-y-2.5">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400 font-mono">
              <HelpCircle className="h-3.5 w-3.5" />
              <span>7. Data Limitations</span>
            </div>
            <ul className="space-y-2 text-xs text-slate-400">
              {report.dataLimitations.map((lim, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-slate-400 font-mono font-bold shrink-0 mt-0.5">
                    *
                  </span>
                  <span>{lim}</span>
                </li>
              ))}
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};
